### ISSUE TITLE
location.timezone is null

### ISSUE THREAD

**Issue by CardenInsurance** [ethayer/lock-manager#24]
I'm using iOS 10.3.1.

I see this error in the logs:
java.lang.NullPointerException @ line 619

This is the line it's referring to:
def today = new Date().format("EEEE", location.timeZone)

When I played with the code, I noticed a line that says "subscribe(location, locationHandler)" and that locationHandler is actually null.

It's possible that the reason the error happens is because, when I installed the SmartThings iOS app, I told iOS to not allow the app to access to GPS.  I re-enabled GPS permissions and reinstalled the app, but it still doesn't work.

**Comment by CardenInsurance** [comment]
I fixed the code but I probably did it poorly.  I don't know how to do a pull requests so here's the whole file I changed (attached).

[fixed timezones.txt](https://github.com/ethayer/lock-manager/files/906252/fixed.timezones.txt)

**Comment by CardenInsurance** [comment]
This bug causes it to be impossible to add a new user.  In my forked code, I replaced the timezone checks with a generic timezone, and now it works well enough to add a user.  I would fix the bug properly and do a pull request if I knew more Java.  Instead, I'll just put my hacked file as an attachment here for anyone desperate enough to use it until a real fix is made.
[Modified file that fixes error about timezones.txt](https://github.com/ethayer/lock-manager/files/906467/Modified.file.that.fixes.error.about.timezones.txt)

**Comment by ethayer** [comment]
Fixed v1.2

**Comment by CardenInsurance** [comment]
I confirm that this problem is now fixed. Thanks!

**Comment by CardenInsurance** [comment]
Sorry!  I made a mistake with updating my code.  This issue is still happening with the official code.  New error is "java.lang.NullPointerException @ line 622".
