### ISSUE TITLE
NewUser page is blank

### ISSUE THREAD

**Issue by khilscher** [ethayer/lock-manager#26]
I've got a Yale YRD240 Z-wave lock. I installed Lock Manager parent and child apps per the v.1.1 instructions at https://dl.dropboxusercontent.com/u/54190708/LockManager/v1.1/guide.pdf

I can lock/unlock the lock just fine. 

However, using the iOS SmartThings app, when I click 'New User' and enter the user name, code and slot and click 'Next' the next page is blank, except for a 'Back' and 'Done'. If I click 'Done' and I get the error 'Error saving unnamed page. Please contact SmartApp developer".

Thanks,

Kevin

**Comment by ethayer** [comment]
Please contact SmartThings support regarding this issue.  I cannot duplicate this.

**Comment by CardenInsurance** [comment]
I had this problem too.  This was caused by issue#24, and is fixed now, at least for me.  I think it happened because an exception was thrown by having a null timezone variable, which caused the rest of the page to not be drawn, rendering it blank.

**Comment by ethayer** [comment]
@khilscher can you confirm that you're no longer getting the blank page?

**Comment by khilscher** [comment]
No, issue still persists. When I go through the iOS app, the page after entering a user, code and slot is blank. In the logs it shows:

2e6e250a-7bb5-42cd-b24a-78c289e5e048 5:00:15 PM: error java.lang.NullPointerException @ line 622
257c3b42-c0f0-4116-be78-7255e38de569 4:59:13 PM: debug there are 1 lock users

**Comment by ethayer** [comment]
Is that after updating to v1.2?

**Comment by khilscher** [comment]
Yes.

**Comment by ethayer** [comment]
huh.. I still can't recreate this issue.  Only thing I can dig up is this: 

```
getTimeZone()
The time zone for the Location. Requires that location services are enabled in the mobile application.
```

Do you have location services disabled on your phone for SmartThings?

**Comment by CardenInsurance** [comment]
Uh oh, I am having the problem again now too.  I think when I said it was fixed the other day, I must have still been using my custom hacked code without realizing it due to some confusion with updating the app.  It seems the SmartThings IDE website has two places for storing code.  It's hard to explain, but if you don't select an item from "My Locations" in the IDE, it acts like it's showing a completely separate repository.  Just now, I selected my location, updated the code again from your repo, published it to my hub, and now the app fails with the blank screen like before.

**Comment by khilscher** [comment]
Yes, location services is enabled for ST.

**Comment by ethayer** [comment]
Ok, I refactored your fix a bit and it's in the master branch now.  Install it and let me know if it works.

**Comment by CardenInsurance** [comment]
Ok, unless I'm mistaken again, it's working now.  However, I'm wondering if TimeZone.getDefault() is returning the correct timezone.  I am in Eastern TimeZone, but I get the value `sun.util.calendar.ZoneInfo[id="Etc/UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]`

**Comment by ethayer** [comment]
nope, that wouldn't be right for ETC.. should be -0500.

Though if SmartThings doesn't know you're ETC I'm not sure how the app would get that info, at least not automagically.  Do you care to ping ST support on why location.timezone doesn't return the correct thing for you?

**Comment by CardenInsurance** [comment]
Ok, I'll email them now

**Comment by ethayer** [comment]
Is it possible you haven't dropped a pin for your hub's location:
on device:
`'More' > cog icon > `

**Comment by khilscher** [comment]
Your code update fixed it for me too! Thank you!

**Comment by CardenInsurance** [comment]
@ethayer I dropped a pin a few days ago.  I just checked it again and it's still in the correct place.

**Comment by ethayer** [comment]
@khilscher Great!  Good to know.

@CardenInsurance let me know what they say about the timezone thing.  I imagine both you and @khilscher don't have correct timezones set on your SmartThings accounts somehow.

**Comment by khilscher** [comment]
Where is the timezone setup in ST?

**Comment by CardenInsurance** [comment]
I think you're right.  On the website, when I click my Location, it says "Time Zone" and is blank.  However, it does show my LatLon coordinates.  If I click Edit, it does not give me any option to set the TimeZone.

**Comment by CardenInsurance** [comment]
I fixed it.  You have to use the app and move your pin to a far away place, click Save, click Done.  Then go back and move the pin back to the correct place, click Save, click Done.  The ST website's Time Zone updates immediately after refreshing the page.

**Comment by CardenInsurance** [comment]
testing the code again.  Now, your new timeZone() method returns the correct value (America\New_York).  TimeZone.getDefault() still returns the ETC/UTC thing, but I think that's a perfect way for your app to handle it.  So if a user has no tz selected in their ST Location, then they'll get the default UTC tz and your app won't crash.

Thanks so much for your help with this!

**Comment by ethayer** [comment]
Nice, thanks for doing that legwork on the timezone stuff.  Sounds like a pretty smelly bug on the ST platform.
